"""Initial schema

Revision ID: 04c9772bd333
Revises: 
Create Date: 2025-05-14 18:15:35.974985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c9772bd333'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_fix_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('num_fixations', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='spd'
    )
    with op.batch_alter_table('mobile_fix_summary', schema='spd') as batch_op:
        batch_op.create_index(batch_op.f('ix_spd_mobile_fix_summary_id'), ['id'], unique=False)

    op.create_table('mobile_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_operator', sa.String(), nullable=False),
    sa.Column('isdn_number', sa.String(), nullable=False),
    sa.Column('time_period', sa.DateTime(), nullable=False),
    sa.Column('imsi_number', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('lac_tac', sa.String(), nullable=True),
    sa.Column('base_station_type', sa.String(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('width', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('base_station_location', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='spd'
    )
    with op.batch_alter_table('mobile_operators', schema='spd') as batch_op:
        batch_op.create_index(batch_op.f('ix_spd_mobile_operators_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_operators', schema='spd') as batch_op:
        batch_op.drop_index(batch_op.f('ix_spd_mobile_operators_id'))

    op.drop_table('mobile_operators', schema='spd')
    with op.batch_alter_table('mobile_fix_summary', schema='spd') as batch_op:
        batch_op.drop_index(batch_op.f('ix_spd_mobile_fix_summary_id'))

    op.drop_table('mobile_fix_summary', schema='spd')
    # ### end Alembic commands ###
